[package]
name = "idgen"
version = "1.2.0"
authors = ["Mohamed Aamir Maniar <aamir.maniar@maniartech.com>"]
edition = "2018"

[dependencies]
uuid = { version = "1.4.1", features = ["v1", "v3", "v4", "v5", "md5", "sha1", "fast-rng", "std"], default-features = false }
bson = { version = "2.7.0", default-features = false }
nanoid = "0.4.0"
cuid = "1.3.3"
ulid = "1.2.1"
